version: '3'
services:
  mongo:
    image: mongo
    container_name: bourse-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

volumes:
  mongo-data:
